### ISSUE TITLE
Docker build broken - npm error

### ISSUE THREAD

**Issue by klaus-aunds** [StJudeWasHere/seonaut#7]
**Describe the bug**
Cloning the repo (checked out at 1ed77d7b10eab47451c6d74ea17431cfd159ade8) and trying to run a docker build fails with the following npm error

```
 => ERROR [front 4/4] RUN npm install esbuild && ./node_modules/esbuild/bin/esbuild ./app/web/css/style.css  --bundle  --minify  --outdir=./app/web/static  --public  2.7s
------
 > [front 4/4] RUN npm install esbuild && ./node_modules/esbuild/bin/esbuild ./app/web/css/style.css 	--bundle 	--minify 	--outdir=./app/web/static 	--public-path=/resources 	--loader:.woff=file 	--loader:.woff2=file:
#0 2.604 npm notice
#0 2.604 npm notice New minor version of npm available! 9.6.7 -> 9.7.1
#0 2.604 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
#0 2.604 npm notice Run `npm install -g npm@9.7.1` to update!
#0 2.604 npm notice
#0 2.605 npm ERR! code 1
#0 2.605 npm ERR! path /home/node/node_modules/esbuild
#0 2.605 npm ERR! command failed
#0 2.605 npm ERR! command sh -c node install.js
#0 2.605 npm ERR! node:internal/errors:496
#0 2.605 npm ERR!     ErrorCaptureStackTrace(err);
#0 2.605 npm ERR!     ^
#0 2.605 npm ERR!
#0 2.606 npm ERR! <ref *1> Error: spawnSync /home/node/node_modules/esbuild/bin/esbuild ETXTBSY
#0 2.606 npm ERR!     at Object.spawnSync (node:internal/child_process:1117:20)
#0 2.606 npm ERR!     at spawnSync (node:child_process:871:24)
#0 2.606 npm ERR!     at Object.execFileSync (node:child_process:914:15)
#0 2.606 npm ERR!     at validateBinaryVersion (/home/node/node_modules/esbuild/install.js:98:28)
#0 2.606 npm ERR!     at /home/node/node_modules/esbuild/install.js:285:5 {
#0 2.606 npm ERR!   errno: -26,
#0 2.606 npm ERR!   code: 'ETXTBSY',
#0 2.606 npm ERR!   syscall: 'spawnSync /home/node/node_modules/esbuild/bin/esbuild',
#0 2.606 npm ERR!   path: '/home/node/node_modules/esbuild/bin/esbuild',
#0 2.606 npm ERR!   spawnargs: [ '--version' ],
#0 2.606 npm ERR!   error: [Circular *1],
#0 2.606 npm ERR!   status: null,
#0 2.606 npm ERR!   signal: null,
#0 2.606 npm ERR!   output: null,
#0 2.606 npm ERR!   pid: 0,
#0 2.606 npm ERR!   stdout: null,
#0 2.606 npm ERR!   stderr: null
#0 2.606 npm ERR! }
#0 2.606 npm ERR!
#0 2.606 npm ERR! Node.js v20.3.0
#0 2.607
#0 2.609 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-06-20T17_22_19_474Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm install esbuild && ./node_modules/esbuild/bin/esbuild ./app/web/css/style.css 	--bundle 	--minify 	--outdir=./app/web/static 	--public-path=/resources 	--loader:.woff=file 	--loader:.woff2=file]: exit code: 1
```

At 4878c788c2e2afcba9f7b1854818a8a8c806c823 the issue is not present.

**To Reproduce**
1. checkout at 1ed77d7b10eab47451c6d74ea17431cfd159ade8
2. run `docker-compose up -d --build`

**Expected behavior**
Build finishes successfully.

PS: thanks a lot for this projects. I just started testing it and it looks terrific!

**Comment by StJudeWasHere** [comment]
Thanks for pointing this out.

For some reason installing esbuild fails with the node 20 version. For now I reverted it back to the previous version in #[8805c28](https://github.com/StJudeWasHere/seonaut/commit/8805c28d3c89136ba7a91f54d2ac516ca255e918) so the docker image can be build.
